spring.application.name=ms-gateway
server.port=${PORT:8090}

services.centros=${CENTROS_URL:http://localhost:8080}
services.biomasa=${BIOMASA_URL:http://localhost:8081}
services.lotes=${LOTES_URL:http://localhost:8082}
services.alimentacion=${ALIMENTACION_URL:http://localhost:8083}
services.ambiental=${AMBIENTAL_URL:http://localhost:8084}
services.sanidad=${SANIDAD_URL:http://localhost:8085}
services.personal=${PERSONAL_URL:http://localhost:8086}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
