spring.application.name=ms-personal

# Puerto exclusivo para evitar colisiones
server.port=8086

# Configuración de la Base de Datos (Cambia db_personal si usas otro nombre en PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/db_personal
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate creará/actualizará las tablas automáticamente al levantar el proyecto
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
