spring.application.name=ms-biomasa
server.port=${PORT:8081}

# Base de datos SQL H2 para desarrollo
spring.datasource.url=jdbc:h2:mem:db_biomasa;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# URL de otros microservicios
app.ms-lotes.url=${LOTES_URL:http://localhost:8082}
