-- Script de referencia para la base de datos del proyecto AquaChiloe.
-- En la aplicacion se usa H2 en memoria y Spring crea las tablas automaticamente,
-- pero se deja este archivo para mostrar la estructura SQL pedida.

CREATE TABLE IF NOT EXISTS jaulas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_jaula VARCHAR(100) NOT NULL,
    centro_id BIGINT NOT NULL,
    activa BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS lotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_lote VARCHAR(100) NOT NULL,
    jaula_id BIGINT NOT NULL,
    cantidad_peces INTEGER NOT NULL,
    fecha_ingreso DATE
);

CREATE TABLE IF NOT EXISTS registros_biomasa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jaula_id BIGINT NOT NULL,
    especie VARCHAR(100) NOT NULL,
    peso_promedio_gramos DOUBLE NOT NULL,
    cantidad_peces INTEGER,
    fecha_muestreo DATE
);

CREATE TABLE IF NOT EXISTS registros_alimentacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jaula_id BIGINT NOT NULL,
    cantidad_alimento_kilos DOUBLE NOT NULL,
    fecha_registro DATE
);

CREATE TABLE IF NOT EXISTS lecturas_ambientales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    centro_id BIGINT NOT NULL,
    sensor_id VARCHAR(100) NOT NULL,
    oxigeno DOUBLE NOT NULL,
    temperatura DOUBLE NOT NULL,
    salinidad DOUBLE NOT NULL,
    fecha_lectura TIMESTAMP,
    alerta_critica BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS tratamientos_sanitarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jaula_id BIGINT NOT NULL,
    medicamento VARCHAR(120) NOT NULL,
    fecha_aplicacion TIMESTAMP NOT NULL,
    dias_carencia INTEGER NOT NULL,
    veterinario_responsable VARCHAR(120),
    observaciones VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS cargos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_cargo VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS trabajadores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rut VARCHAR(20) NOT NULL,
    nombre VARCHAR(120) NOT NULL,
    turno VARCHAR(50) NOT NULL,
    cargo_id BIGINT,
    CONSTRAINT fk_trabajador_cargo FOREIGN KEY (cargo_id) REFERENCES cargos(id)
);

INSERT INTO jaulas (codigo_jaula, centro_id, activa) VALUES ('JAULA-01', 1, TRUE);
INSERT INTO lotes (codigo_lote, jaula_id, cantidad_peces, fecha_ingreso) VALUES ('LOTE-01', 1, 1200, CURRENT_DATE);
INSERT INTO registros_biomasa (jaula_id, especie, peso_promedio_gramos, cantidad_peces, fecha_muestreo) VALUES (1, 'Salmon Atlantico', 850, 1200, CURRENT_DATE);
INSERT INTO registros_alimentacion (jaula_id, cantidad_alimento_kilos, fecha_registro) VALUES (1, 45, CURRENT_DATE);
INSERT INTO lecturas_ambientales (centro_id, sensor_id, oxigeno, temperatura, salinidad, fecha_lectura, alerta_critica) VALUES (1, 'SENSOR-01', 5.2, 12.5, 30, CURRENT_TIMESTAMP, TRUE);
INSERT INTO tratamientos_sanitarios (jaula_id, medicamento, fecha_aplicacion, dias_carencia, veterinario_responsable, observaciones) VALUES (1, 'Antiparasitario', CURRENT_TIMESTAMP, 14, 'Dr. Perez', 'Tratamiento preventivo');
INSERT INTO cargos (nombre_cargo) VALUES ('Operario');
INSERT INTO trabajadores (rut, nombre, turno, cargo_id) VALUES ('12345678-9', 'Juan Soto', 'Manana', 1);
